apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
