redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  service:
    type: LoadBalancer

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

configs:
  secret:
    argocdServerAdminPassword: "admin"
  cm:
    #use annotation for tracking but keep labels for compatibility with other tools
    application.resourceTrackingMethod: annotation+label
    